# SPDX-License-Identifier: GPL-2.0-only
#
# Makefile for Mellanox NODNIC driver
#

obj-$(CONFIG_MLX5_NODNIC) += mlx5_nodnic.o

mlx5_nodnic-y := main.o en.o en_cfg.o tx.o rx.o nodnic_pci_vsc.o health.o